### ISSUE TITLE
snapshot-manager 1.02's upload isn't working in MacOS Sierra

### ISSUE THREAD

**Issue by whi-tw** [Memset/snapshot-manager#2]
This could be related to golang/go#16570

```
snapshot-manager upload MyCoolImage MyImage.raw

2016/11/07 10:27:29 Uploading snapshot
2016/11/07 10:27:29 Gzipping on the fly
failed MSpanList_Insert 0x569e18 0x31f6aa4d0a18b 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.MSpanList_Insert(0x4da670, 0x569e18)
	/home/ncw/Code/go/src/runtime/mheap.c:692 +0x8f
runtime.MHeap_Alloc(0x4da120, 0x2, 0x10000000026, 0xf359)
	/home/ncw/Code/go/src/runtime/mheap.c:240 +0x66
runtime.MCentral_CacheSpan(0x4e3518, 0x35d28)
	/home/ncw/Code/go/src/runtime/mcentral.c:85 +0x167
runtime.MCache_Refill(0x53ce10, 0x26, 0x800569938)
	/home/ncw/Code/go/src/runtime/mcache.c:90 +0xa0

goroutine 21 [running]:
runtime.switchtoM()
	/home/ncw/Code/go/src/runtime/asm_amd64.s:198 fp=0xc2080dd920 sp=0xc2080dd918
runtime.mallocgc(0x900, 0x2dcd40, 0xc200000001, 0x40)
	/home/ncw/Code/go/src/runtime/malloc.go:178 +0x849 fp=0xc2080dd9d0 sp=0xc2080dd920
runtime.newarray(0x2dcd40, 0x11f, 0xc20808c1c8)
	/home/ncw/Code/go/src/runtime/malloc.go:365 +0xc1 fp=0xc2080dda08 sp=0xc2080dd9d0
runtime.makeslice(0x24ece0, 0x11f, 0x11f, 0x0, 0x0, 0x0)
	/home/ncw/Code/go/src/runtime/slice.go:32 +0x15c fp=0xc2080dda50 sp=0xc2080dda08
compress/flate.(*huffmanEncoder).generate(0xc2082a4000, 0xc2080ae000, 0x11e, 0x11e, 0xf)
	/home/ncw/Code/go/src/compress/flate/huffman_code.go:264 +0x47 fp=0xc2080ddae8 sp=0xc2080dda50
compress/flate.(*huffmanBitWriter).writeBlock(0xc20808c0f0, 0xc2081ce000, 0x4001, 0x4001, 0x4000, 0xc20830d036, 0x405e, 0xafca)
	/home/ncw/Code/go/src/compress/flate/huffman_bit_writer.go:414 +0x306 fp=0xc2080ddc08 sp=0xc2080ddae8
compress/flate.(*compressor).writeBlock(0xc2080c0240, 0xc2081ce000, 0x4000, 0x4001, 0x9094, 0x0, 0x0, 0x0)
	/home/ncw/Code/go/src/compress/flate/deflate.go:142 +0x123 fp=0xc2080ddc68 sp=0xc2080ddc08
compress/flate.(*compressor).deflate(0xc2080c0240)
	/home/ncw/Code/go/src/compress/flate/deflate.go:348 +0xecf fp=0xc2080ddd50 sp=0xc2080ddc68
compress/flate.(*compressor).write(0xc2080c0240, 0xc208336000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
	/home/ncw/Code/go/src/compress/flate/deflate.go:379 +0xc7 fp=0xc2080ddd80 sp=0xc2080ddd50
compress/flate.(*Writer).Write(0xc2080c0240, 0xc208336000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
	/home/ncw/Code/go/src/compress/flate/deflate.go:534 +0x5f fp=0xc2080dddc0 sp=0xc2080ddd80
compress/gzip.(*Writer).Write(0xc208334000, 0xc208336000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
	/home/ncw/Code/go/src/compress/gzip/gzip.go:219 +0x60e fp=0xc2080dde80 sp=0xc2080dddc0
io.Copy(0x55a760, 0xc208334000, 0x54df30, 0xc208326050, 0x7420000, 0x0, 0x0)
	/home/ncw/Code/go/src/io/io.go:364 +0x278 fp=0xc2080ddf38 sp=0xc2080dde80
github.com/memset/snapshot-manager/snapshot.func·001()
	/home/ncw/Code/Go/src/github.com/memset/snapshot-manager/snapshot/gzip.go:33 +0x8b fp=0xc2080ddfe0 sp=0xc2080ddf38
runtime.goexit()
	/home/ncw/Code/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080ddfe8 sp=0xc2080ddfe0
created by github.com/memset/snapshot-manager/snapshot.NewGzipReader
	/home/ncw/Code/Go/src/github.com/memset/snapshot-manager/snapshot/gzip.go:37 +0x2da

goroutine 1 [chan receive]:
github.com/memset/snapshot-manager/snapshot.(*Snapshot).putChunkedFile(0xc2080f0000, 0x55a738, 0xc2082a84a0, 0x370ad0, 0x14, 0xc2082a8440, 0x1b, 0x370ad0, 0x14, 0xc2082c21e0, ...)
	/home/ncw/Code/Go/src/github.com/memset/snapshot-manager/snapshot/snapshot.go:223 +0x5c7
github.com/memset/snapshot-manager/snapshot.(*Snapshot).Put(0xc2080f0000, 0x7fff5fbff8c1, 0xf, 0x0, 0x0)
	/home/ncw/Code/Go/src/github.com/memset/snapshot-manager/snapshot/snapshot.go:385 +0x1850
main.uploadSnaphot(0x7fff5fbff8b8, 0x8, 0x7fff5fbff8c1, 0xf)
	/home/ncw/Code/Go/src/github.com/memset/snapshot-manager/main.go:122 +0xc6
main.func·003()
	/home/ncw/Code/Go/src/github.com/memset/snapshot-manager/main.go:214 +0x7b
main.main()
	/home/ncw/Code/Go/src/github.com/memset/snapshot-manager/main.go:260 +0x780

goroutine 37 [select]:
net/http.(*persistConn).writeLoop(0xc2080a86e0)
	/home/ncw/Code/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/home/ncw/Code/go/src/net/http/transport.go:661 +0xcbc

goroutine 7 [sleep]:
net.func·019()
	/home/ncw/Code/go/src/net/dnsclient_unix.go:240 +0x5a
created by net.loadConfig
	/home/ncw/Code/go/src/net/dnsclient_unix.go:269 +0x20c

goroutine 36 [IO wait]:
net.(*pollDesc).Wait(0xc20829e370, 0x72, 0x0, 0x0)
	/home/ncw/Code/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20829e370, 0x0, 0x0)
	/home/ncw/Code/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc20829e310, 0xc208114400, 0x400, 0x400, 0x0, 0x54db70, 0xc20829c220)
	/home/ncw/Code/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc208034088, 0xc208114400, 0x400, 0x400, 0x0, 0x0, 0x0)
	/home/ncw/Code/go/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0xc2082a4840, 0x5504b8, 0xc208034088, 0x5, 0x0, 0x0)
	/home/ncw/Code/go/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0xc20827e000, 0x17, 0x0, 0x0)
	/home/ncw/Code/go/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).Read(0xc20827e000, 0xc208103000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/ncw/Code/go/src/crypto/tls/conn.go:904 +0x166
net/http.noteEOFReader.Read(0x559fa0, 0xc20827e000, 0xc2080a8738, 0xc208103000, 0x1000, 0x1000, 0xc20828a1c0, 0x0, 0x0)
	/home/ncw/Code/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc2082b1960, 0xc208103000, 0x1000, 0x1000, 0xc208013200, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc20805aba0)
	/home/ncw/Code/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc20805aba0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/ncw/Code/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc2080a86e0)
	/home/ncw/Code/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/home/ncw/Code/go/src/net/http/transport.go:660 +0xc9f

goroutine 22 [semacquire]:
sync.(*Cond).Wait(0xc208332030)
	/home/ncw/Code/go/src/sync/cond.go:62 +0x9e
io.(*pipe).read(0xc208332000, 0xc209f25ff6, 0x241800a, 0x241800a, 0x0, 0x0, 0x0)
	/home/ncw/Code/go/src/io/pipe.go:52 +0x303
io.(*PipeReader).Read(0xc208326060, 0xc209f25ff6, 0x241800a, 0x241800a, 0x40, 0x0, 0x0)
	/home/ncw/Code/go/src/io/pipe.go:134 +0x5b
github.com/memset/snapshot-manager/snapshot.(*GzipReader).Read(0xc2082580a0, 0xc209f25ff6, 0x241800a, 0x241800a, 0x40, 0x0, 0x0)
	/home/ncw/Code/Go/src/github.com/memset/snapshot-manager/snapshot/gzip.go:53 +0x98
io.(*teeReader).Read(0xc2082a84a0, 0xc209f25ff6, 0x241800a, 0x241800a, 0x40, 0x0, 0x0)
	/home/ncw/Code/go/src/io/io.go:495 +0x83
io.ReadAtLeast(0x55a738, 0xc2082a84a0, 0xc20833e000, 0x4000000, 0x4000000, 0x4000000, 0x1be7ff6, 0x0, 0x0)
	/home/ncw/Code/go/src/io/io.go:298 +0xf1
io.ReadFull(0x55a738, 0xc2082a84a0, 0xc20833e000, 0x4000000, 0x4000000, 0x4000000, 0x0, 0x0)
	/home/ncw/Code/go/src/io/io.go:316 +0x6d
github.com/memset/snapshot-manager/snapshot.func·004()
	/home/ncw/Code/Go/src/github.com/memset/snapshot-manager/snapshot/snapshot.go:189 +0x114
created by github.com/memset/snapshot-manager/snapshot.(*Snapshot).putChunkedFile
	/home/ncw/Code/Go/src/github.com/memset/snapshot-manager/snapshot/snapshot.go:206 +0x43b

goroutine 23 [chan receive]:
github.com/memset/snapshot-manager/snapshot.func·005()
	/home/ncw/Code/Go/src/github.com/memset/snapshot-manager/snapshot/snapshot.go:210 +0xa9
created by github.com/memset/snapshot-manager/snapshot.(*Snapshot).putChunkedFile
	/home/ncw/Code/Go/src/github.com/memset/snapshot-manager/snapshot/snapshot.go:220 +0x580
```

**Comment by whi-tw** [comment]
I've just rebuilt it from source, and it is now uploading correctly.

**Comment by ncw** [comment]
Yes, Apple changed their kernel interface for Sierra which required a change in the go compiler so recompiling it with the latest go compiler is the correct fix.

What I should do is upload new binaries compiled with latest Go

**Comment by ncw** [comment]
I've pushed out a 1.03 release compiled with new compiler so should be all fixed!
